### ISSUE TITLE
random inputs cause byteboy to crash

### ISSUE THREAD

**Issue by itpun** [aptmac/byteboy#13]
Steps to reproduce:

1) start byteboy.java normally
2) when given the choice of what to do next (generation, exit, etc), type something thats not a number

program crashes. :'(

**Comment by aptmac** [comment]
Interesting, and you're running it with no arguments right? The "java_file" variable should be set to false and then redirect the program in the if-statement to not allow those options.

**Comment by aptmac** [comment]
wait nvm thats just the number part .. i'll add another else branch. It should only accept the number option the user wants, having to parse strings and worry about upper/lower case/spelling/etc. would be annoying

**Comment by aptmac** [comment]
Fixed in: https://github.com/aptmac/byteboy/commit/03cf2e87a20192df917dd6080ea2e3ac2d247842
