### ISSUE TITLE
Decide on base-line functionality

### ISSUE THREAD

**Issue by aptmac** [aptmac/byteboy#2]
What are the "must-haves" for the initial design of the application? This could, but is not limited to:

- CLI Tooling
- Language Server
- IDE Extension

And how are we going to get there?

- How are we going to gather Java classes/methods/variables/etc. from an existing program?
- How will the above values be presented to the user?
- What will the UX be like?

**Comment by itpun** [comment]
I think we should either focus on CLI Tooling or the language server, and we can confirm which one would be better to use with Nick.
