### ISSUE TITLE
Resources to utilize

### ISSUE THREAD

**Issue by aptmac** [aptmac/byteboy#3]
**Byteman 3.0.10 (Apr. 2017) Programmer's Guide**
http://downloads.jboss.org/byteman/3.0.10/ProgrammersGuide.html

**A Byteman Tutorial**
https://developer.jboss.org/wiki/ABytemanTutorial#top

**Checking Your Byteman Rule Scripts Under Maven**
https://developer.jboss.org/wiki/CheckingYourBytemanRuleScriptsUnderMaven

**Fault Injection Testing with Byteman**
https://developer.jboss.org/wiki/FaultInjectionTestingWithByteman#top

**Flexible, dynamic injection of structured advice using byteman. (2011).**
Link from SFU library: https://dl-acm-org.proxy.lib.sfu.ca/citation.cfm?id=1960325

**Link to Presentations and Papers**
http://byteman.jboss.org/docs.html

**Comment by itpun** [comment]
https://www.quora.com/How-do-I-use-Bash-to-get-all-class-names-in-a-Java-file

This could be useful for getting class names
